name: Build iOS
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-ios.yml'
      - 'ios/**'
      - '*.podspec'
      - 'example/ios/**'
  pull_request:
    paths:
      - '.github/workflows/build-ios.yml'
      - 'ios/**'
      - '*.podspec'
      - 'example/ios/**'
jobs:
  build:
    name: Build iOS example app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install pods
        run: yarn example pods
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build app
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace VoiceKitExample.xcworkspace \
          -scheme VoiceKitExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
        working-directory: example/ios
