name: Build Android
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'example/android/**'
  pull_request:
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'example/android/**'
jobs:
  build:
    name: Build Android example app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build app
        run: './gradlew assembleDebug --no-daemon --build-cache'
        working-directory: example/android
      - name: Stop Gradle Daemon
        run: ./gradlew --stop
        working-directory: example/android
