name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: 'help wanted,in progress,pinned'
          exempt-pr-labels: 'in progress,pinned'
  stale-missing-info:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          any-of-labels: 'repro-missing'
          stale-issue-message: 'This issue is stale because it is missing information. Please add the requested information or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it is missing information. Please add the requested information or this will be closed in 7 days.'
          days-before-stale: 14
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
